### ISSUE TITLE
About the training source code for both model-guided and neural-guided disentanglement

### ISSUE THREAD

**Issue by guyleaf** [astra-vision/GuidedDisent#1]
Hi, thank you for making this great work!
The results look very impressive and realistic.

I'm creating a UAV dataset for challenging weather conditions and looking for adverse weather generation.
I'd like to know if the training source code would be open-sourced, including model-guided and neural-guided disentanglement.

If you could also open-source other generations, e.g. fog, snowy, it would be beneficial for my project.

Thanks

**Comment by fabvio** [comment]
Hi and thanks for your interest. Unfortunately, I don't have access to the training code anymore, but once you have the physical model, it's extremely easy to reimplement using any kind of GAN framework: it's one line of code where you apply the physical model provided in this repo before forwarding the images to the discriminator. I don't have a snowy model, while for fog I advise you refer to the paper we are citing. It's a very simple implementation.
